Description: Create Simple S3 bucket
Parameters:
  EnvironmentName:
    Description: An Prefix name that is prefixed to resource names
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
    Default: dev

  BucketPrefix:
    Description: An Prefix name that is prefixed to resource names
    Type: String
    Default: your-name

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Description: Demo bucket
    Properties:
      BucketName: !Sub ${EnvironmentName}-${BucketPrefix}-s3-dva-cfn-demo

Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref S3Bucket